export const BASE='/allah/api/hehe/v69/docs';
export const actions=['giveGold','setGold','giveGems','setGems','setLevel','giveItem','setItem','deleteItem'];
export function specification(){
 const response={description:'Successful response',content:{'application/json':{schema:{type:'object'}}}};
 const errors=Object.fromEntries([400,401,403,404,409,429,500].map(x=>[x,{description:x===409?'Revision conflict, duplicate requestId or equipped item.': 'Request rejected',content:{'application/json':{schema:{type:'object',properties:{error:{type:'string'}}}}}}]));
 const page=[{in:'query',name:'limit',schema:{type:'integer',minimum:1,maximum:100,default:25}},{in:'query',name:'offset',schema:{type:'integer',minimum:0,default:0}}];
 const id={in:'path',name:'id',required:true,schema:{type:'string',pattern:'^[a-f0-9]{32}$'},description:'Player ID returned by GET /api/players.'};
 const paths={};
 for(const name of ['players','accounts','catalog','audit'])paths['/api/'+name]={get:{tags:[name==='audit'?'Audit':'Query'],summary:'List '+name,parameters:[...page,{in:'query',name:name==='audit'?'player':'q',schema:{type:'string'}}],responses:{200:response,...errors}}};
 paths['/api/events']={get:{tags:['Events'],summary:'List event manifests',description:'Returns the current version of each event and its server-computed state.',responses:{200:response,...errors}},post:{tags:['Events'],summary:'Publish a future event manifest',description:'Creates a new event version. Event IDs are immutable; publish a higher version to change a schedule or use the disable endpoint for a kill switch.',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['id','version','type','startAt','endAt','config','rewards'],properties:{id:{type:'string',pattern:'^[a-z0-9][a-z0-9_-]{2,63}$'},version:{type:'integer',minimum:1},type:{type:'string'},title:{type:'string'},description:{type:'string'},startAt:{type:'string',format:'date-time'},endAt:{type:'string',format:'date-time'},disabled:{type:'boolean'},config:{type:'object'},rewards:{type:'array',items:{type:'object'}}}}}}},responses:{200:response,...errors}}};
 paths['/api/events/preview']={post:{tags:['Events'],summary:'Preview an event without publishing',description:'Validates and normalizes a manifest, computes its state at previewAt (or current server time), and reports its next schedule boundary. This operation is read-only and does not create an event version.',requestBody:{required:true,content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['manifest'],properties:{manifest:{type:'object',required:['id','version','type','startAt','endAt','config'],properties:{id:{type:'string'},version:{type:'integer',minimum:1},type:{type:'string'},title:{type:'string'},description:{type:'string'},startAt:{type:'string',format:'date-time'},endAt:{type:'string',format:'date-time'},disabled:{type:'boolean'},config:{type:'object'},rewards:{type:'array',items:{type:'object'}}}},previewAt:{type:'string',format:'date-time',description:'Optional ISO-8601 UTC timestamp ending in Z for staging a future schedule check.'}}}}}},responses:{200:response,...errors}}};
 paths['/api/events/{id}/disable']={post:{tags:['Events'],summary:'Disable an event',parameters:[{in:'path',name:'id',required:true,schema:{type:'string',pattern:'^[a-z0-9][a-z0-9_-]{2,63}$'}}],requestBody:{required:false,content:{'application/json':{schema:{type:'object'}}}},responses:{200:response,...errors}}};
 paths['/api/players/{id}']={get:{tags:['Query'],summary:'Read full player profile (no credentials)',parameters:[id],responses:{200:response,...errors}}};
 for(const action of actions){
  const item=action.endsWith('Item');const properties={requestId:{type:'string',minLength:8,maxLength:80,example:'support-case-001'},reason:{type:'string',minLength:3,maxLength:300,example:'Playtest reward correction'},expectedRevision:{type:'integer',minimum:0,example:0,description:'Use profile.AdminRevision from the latest player read.'},...(item?{itemId:{type:'string',example:'spear-1'},tier:{type:'integer',minimum:1,maximum:5,example:1},...(action!=='deleteItem'?{quantity:{type:'integer',minimum:action==='giveItem'?1:0,maximum:1000000,example:5}}:{}),unequip:{type:'boolean',default:false,description:'Explicitly clear gear/book slots when deleting the last owned copy.'}}:{amount:{type:'integer',minimum:action==='setLevel'||action.startsWith('give')?1:0,maximum:action==='setLevel'?1000000:2000000000,example:action==='setLevel'?10:100}})};
  paths[`/api/players/{id}/${action}`]={[action==='deleteItem'?'delete':'post']:{tags:[item?'Inventory':'Currency and level'],operationId:action,summary:action,description:'Atomic, audited and idempotent. Retry with the SAME requestId/body after a timeout; use a NEW requestId for a new change. Set currency to zero to clear it. setItem creates/replaces a stack; quantity zero removes it. Character Level is separate from campaign progress and does not grant combat stats or unlock stages. Reconnect the game to refresh an online profile.',parameters:[id],requestBody:{required:true,content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['requestId','reason','expectedRevision',...(item?['itemId','tier',...(action==='deleteItem'?[]:['quantity'])]:['amount'])],properties}}}},responses:{200:response,...errors}}};
 }
 return {openapi:'3.0.3',info:{title:'Echoes of the Rift — Local Admin API',version:'1.0.0',description:'LOCAL ADMIN ONLY. Click Authorize and enter your configured admin username/password. List accounts/players, copy the player ID, read its profile and AdminRevision, then make a correction. All edits use a unique requestId and reason. Gold is stored as Coins. Gems/Level are persistent fields; gem economy and level scaling are separate development milestones. Passwords and authentication tokens are never returned. Swagger assets are served locally.'},servers:[{url:BASE}],security:[{AdminLogin:[]}],components:{securitySchemes:{AdminLogin:{type:'http',scheme:'basic',description:'Local administrator username and password. Loopback only; public deployment requires HTTPS and separate access controls.'}}},paths};
}
