import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import http from 'node:http';
import {startAdmin} from './admin.mjs';
import {createStore} from './persistence.mjs';
import {createAccounts} from './accounts.mjs';
import {createAdminStore} from './admin-store.mjs';
import {mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createAdminCredentials,verifyAdmin} from './admin-auth.mjs';
import {BASE} from './admin-openapi.mjs';
const credentials=await createAdminCredentials('test_admin','disposable-test-password');
const authorization='Basic '+Buffer.from('test_admin:disposable-test-password').toString('base64');
assert.equal(await verifyAdmin(authorization,credentials),true);
assert.equal(JSON.stringify(credentials).includes('disposable-test-password'),false);
const id='a'.repeat(32),secret='b'.repeat(64);
const catalog=[{id:'gear-0',kind:0,slot:0,tier:1},{id:'book-1',kind:1,slot:0,tier:1,skill:'test-skill'}];
const app=startAdmin({port:0,path:':memory:',credentials,catalog});await once(app.server,'listening');const port=app.server.address().port,base=`http://127.0.0.1:${port}${BASE}`;
try{
 app.store.login(id,secret);let revision=0;
 const call=async(path,body,method='POST',headers={})=>{const res=await fetch(base+path,{method,headers:{authorization,'content-type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,body:await res.json()};};
 const mutate=async(action,fields={},status=200)=>{const b={requestId:randomUUID(),reason:'Automated disposable test',expectedRevision:revision,...fields};const result=await call(`/api/players/${id}/${action}`,b,action==='deleteItem'?'DELETE':'POST');assert.equal(result.status,status,JSON.stringify(result.body));if(status===200)revision=result.body.profile.AdminRevision;return {b,result};};
 assert.equal((await fetch(base+'/api/players')).status,401);
 assert.equal((await call('/api/players',undefined,'GET',{origin:'https://untrusted.invalid'})).status,403);
 const hostile=await new Promise(resolve=>{http.get({host:'127.0.0.1',port,path:'/docs',headers:{host:`attacker.invalid:${port}`}},r=>{r.resume();resolve(r.statusCode);});});assert.equal(hostile,403);
 assert.equal((await fetch(`http://127.0.0.1:${port}/docs`)).status,404);
 assert.equal((await call('/api/players',undefined,'GET',{authorization:'Basic '+Buffer.from('test_admin:incorrect').toString('base64')})).status,401);
 assert.equal((await fetch(base+'/')).status,200);assert.match(await(await fetch(base+'/init.js')).text(),/validatorUrl:null/);
 const spec=await(await fetch(base+'/openapi.json')).json();assert.equal(Object.keys(spec.paths).length,15);assert.ok(spec.paths['/api/players/{id}/deleteItem'].delete);assert.ok(spec.paths['/api/events'].post);assert.ok(spec.paths['/api/events/{id}/disable'].post);
 const event={id:'autumn-test',version:1,type:'token_exchange',title:'Autumn Test',startAt:'2026-10-01T00:00:00.000Z',endAt:'2026-10-08T00:00:00.000Z',config:{tokenId:'autumn-token'},rewards:[]};
 const published=await call('/api/events',event);assert.equal(published.status,200,JSON.stringify(published.body));assert.equal((await call('/api/events',undefined,'GET')).body.events.length,1);
 const disabled=await call('/api/events/autumn-test/disable',{},'POST');assert.equal(disabled.status,200,JSON.stringify(disabled.body));assert.equal(disabled.body.disabled,true);
 let {b,result}=await mutate('giveGold',{amount:100});assert.equal(result.body.profile.Coins,130);
 const replay=await call(`/api/players/${id}/giveGold`,b);assert.equal(replay.body.replayed,true);assert.equal(app.store.get(id).Coins,130);
 assert.equal((await call(`/api/players/${id}/giveGold`,{...b,amount:200})).status,409);
 await mutate('setGold',{amount:9,expectedRevision:0},409);await mutate('setGold',{amount:-1},400);await mutate('giveGold',{amount:0.5},400);
 await mutate('giveGold',{amount:2000000000},400);await mutate('setGold',{amount:0});
 await mutate('giveGems',{amount:50});await mutate('setGems',{amount:0});await mutate('setLevel',{amount:25});await mutate('setLevel',{amount:0},400);
 await mutate('giveItem',{itemId:'book-1',tier:1,quantity:3});await mutate('setItem',{itemId:'book-1',tier:1,quantity:7});
 await mutate('giveItem',{itemId:'unknown',tier:1,quantity:1},400);await mutate('giveItem',{itemId:'book-1',tier:6,quantity:1},400);
 await mutate('deleteItem',{itemId:'gear-0',tier:1},409);await mutate('deleteItem',{itemId:'gear-0',tier:1,unequip:true});assert.equal(app.store.get(id).EquippedIds[0],'');
 app.store.transaction(id,'skill','book-1',1);revision=app.store.get(id).AdminRevision;
 await mutate('deleteItem',{itemId:'book-1',tier:1},409);await mutate('deleteItem',{itemId:'book-1',tier:1,unequip:true});assert.equal(app.store.get(id).SkillIds[0],'');
 await mutate('deleteItem',{itemId:'book-1',tier:1},404);
 const legacy=app.store.get(id);delete legacy.Level;delete legacy.Gems;delete legacy.AdminRevision;app.store.db.prepare('UPDATE players SET profile=? WHERE id=?').run(JSON.stringify(legacy),id);
 const migrated=(await call('/api/players/'+id,undefined,'GET')).body.profile;assert.equal(migrated.Level,1);assert.equal(migrated.Gems,0);revision=0;
 await mutate('setGems',{amount:123});await mutate('setLevel',{amount:12});app.store.transaction(id,'reward','',0,'12345678',0);revision=app.store.get(id).AdminRevision;
 assert.equal(app.store.get(id).Gems,123);assert.equal(app.store.get(id).Level,12);
 await mutate('setGold',{amount:200,expectedRevision:revision-1},409);
 const users=await call('/api/players',undefined,'GET');assert.equal(users.body.players.length,1);assert.equal(JSON.stringify(users).includes(secret),false);
 await createAccounts(app.store).register({username:'admin_query_fixture',password:'disposable testing passphrase'});
 const named=await call('/api/players?q=admin_query_fixture',undefined,'GET');assert.equal(named.body.players.length,1);
 const catalogResult=await call('/api/catalog?q=gear',undefined,'GET');assert.equal(catalogResult.body.total,1);
 const accounts=await call('/api/accounts',undefined,'GET');assert.deepEqual(Object.keys(accounts.body.accounts[0]).sort(),['player','username']);assert.equal(accounts.status,200);assert.equal(JSON.stringify(accounts).includes('password'),false);
 const history=await call('/api/audit',undefined,'GET');assert.ok(history.body.entries.length>=10);assert.ok(history.body.entries.every(x=>x.before&&x.after&&x.reason));
 const before=JSON.stringify(app.store.get(id));await mutate('setGold',{amount:'100'},400);assert.equal(JSON.stringify(app.store.get(id)),before);
 const simultaneous=await Promise.all([1,2].map(amount=>call(`/api/players/${id}/giveGold`,{requestId:randomUUID(),reason:'Concurrent correction test',expectedRevision:revision,amount})));assert.deepEqual(simultaneous.map(x=>x.status).sort(),[200,409]);
 for(let attempt=0;attempt<8;attempt++)assert.equal((await fetch(base+'/api/players')).status,401);
 assert.equal((await fetch(base+'/api/players')).status,429);
 console.log('PASS admin: auth/Host/Origin protections; Swagger; player/account/catalog queries; grant/set/remove; bounds and unknown items; equipment/book protection; replay/conflict; legacy defaults; gameplay preservation; audit atomicity; concurrent revision conflict.');
}finally{await new Promise(resolve=>app.server.close(resolve));app.store.db.close();}

const directory=new URL('../Logs/AdminTests/',import.meta.url);mkdirSync(directory,{recursive:true});
const diskPath=fileURLToPath(new URL(randomUUID()+'.sqlite',directory));
let disk=createStore(diskPath,catalog);createAccounts(disk);disk.login(id,secret);
const request={requestId:randomUUID(),reason:'Durable grant across restart',expectedRevision:0,amount:77};
createAdminStore(disk,catalog).mutate(id,'giveGems',request);disk.db.close();
disk=createStore(diskPath,catalog);const reopened=createAdminStore(disk,catalog);
assert.equal(disk.get(id).Gems,77);assert.equal(reopened.mutate(id,'giveGems',request).replayed,true);assert.equal(disk.get(id).Gems,77);assert.equal(reopened.audit({}).entries.length,1);disk.db.close();
console.log('PASS durable admin grant and audit survive database reopen; replay does not duplicate gems.');
